// controllers/hostController.js
const Home = require("../models/home");
const fs = require('fs');
const path = require('path'); 
const User = require('../models/user');

exports.getHost = (req, res, next) => {
  res.render('host/edit-home', {
    pageTitle: "Add Venue",
    title: 'form',
    editing: false, 
    isLoggedIn: req.isLoggedIn,
    user: {}
  });
};

exports.postHost = async (req, res, next) => {
  try {
    // 1. Extract data (including new fields: capacity, venueType)
    const { 
      housename, 
      address, 
      price, 
      rating, 
      facilities, 
      hostEmail, 
      capacity, 
      venueType 
    } = req.body;

    // 2. Handle Image Upload
    const images = req.files?.photoUrl;
    if (!images || images.length === 0) {
      return res.status(422).send("No image provided");
    }
    const photoUrl = images[0].path.replace(/\\/g, "/");

    // 3. Handle PDF Upload (FIXED: No renaming)
    let rulesPdfUrl = null;
    if (req.files?.houseRulesPdf && req.files.houseRulesPdf.length > 0) {
      // We use the unique filename generated by Multer automatically.
      // This prevents the "EPERM" error and prevents files from overwriting each other.
      rulesPdfUrl = req.files.houseRulesPdf[0].path.replace(/\\/g, "/");
    }

    // 4. Find the Host User
    const user = await User.findOne({ email: hostEmail });
    if (!user) return res.status(404).send("Host not found");

    // 5. Create the Venue Object
    const home = new Home({
      housename,
      address,
      capacity,    // New Field
      venueType,   // New Field
      price,
      rating,
      photoUrl,
      facilities,
      hostEmail,
      host: user._id,
      rulesPdfUrl, // Saves the path to the PDF
    });

    // 6. Save to Database
    await home.save();
    console.log('Venue saved successfully');
    res.redirect('/home-list');

  } catch(err) {
    console.log('Error saving venue:', err);
    next(err);
  }
};

exports.getHostList = async (req, res, next) => {
  try {
    if (!req.session?.isLoggedIn || !req.session?.user) {
      return res.status(401).send("Unauthorized: User not logged in");
    }

    const hostId = req.session.user._id; 

    const registeredHomes = await Home.find({ host: hostId })
      .populate('host', 'firstname email'); 

    console.log("Venues found for host", hostId, registeredHomes.length);

    return res.render("host/host-home-list", {
      homes: registeredHomes,
      pageTitle: "My Properties",
      isLoggedIn: req.session.isLoggedIn,
      user: req.session.user
    });
  } catch (err) {
    console.error("Error fetching host venues:", err);
    return res.status(500).send("Server Error");
  }
};

exports.getEditHome = (req, res, next) => {
  const homeId = req.params.homeId;
  const editing = req.query.editing === 'true';

  Home.findById(homeId).then(home => {
    if (!home) {
      console.log("Venue not found for editing.");
      return res.redirect("/host-home-list");
    }
    
    res.render("host/edit-home", {
      home: home,
      pageTitle: "Edit your Venue",
      currentPage: "host-homes",
      editing: editing,
      isLoggedIn: req.isLoggedIn,
      user: {}
    });
  });
};

exports.postEditHome = (req, res, next) => {
  // UPDATED: Destructuring new fields
  const { 
    id, 
    housename, 
    address, 
    price, 
    rating, 
    facilities, 
    hostEmail,
    capacity,    // NEW
    venueType    // NEW
  } = req.body;

  const images = req.files && req.files.photoUrl;        
  const pdfs = req.files && req.files.houseRulesPdf;    

  Home.findById(id)
    .then((home) => {
      if (!home) {
        return res.redirect('/host-home-list');
      }

      home.housename = housename;
      home.address = address;
      // Removed housenumber assignment
      home.capacity = capacity;     // NEW
      home.venueType = venueType;   // NEW
      home.price = price;
      home.rating = rating;
      home.facilities = facilities;
      home.hostEmail = hostEmail;

      // If a new image was uploaded, delete old and set new one
      if (images && images.length > 0) {
        if (home.photoUrl) {
          fs.unlink(home.photoUrl, (err) => {
            if (err) console.log('Error deleting old image:', err);
          });
        }
        home.photoUrl = images[0].path;
      }

      // If a new PDF uploaded, delete old pdf and set new one
      if (pdfs && pdfs.length > 0) {
        if (home.rulesPdfUrl) {
          fs.unlink(home.rulesPdfUrl, (err) => {
            if (err) console.log('Error deleting old pdf:', err);
          });
        }
        home.rulesPdfUrl = pdfs[0].path;
      }

      return home.save();
    })
    .then(result => {
      console.log('Venue updated ', result);
      res.redirect('/host-home-list');
    })
    .catch(err => {
      console.log('error while updating venue', err);
      next(err);
    });
}

exports.postDeleteHome = (req, res, next) => {
  const homeId = req.params.homeId;
  console.log('Came to delete ', homeId);
  Home.findOneAndDelete({_id: homeId}).then(() => {
    res.redirect("/host-home-list");
  }).catch(error => {
    console.log('Error while deleting ', error);
  })
};
const Booking = require("../models/booking");
exports.getHostBookings = async (req, res, next) => {
  const homeId = req.params.homeId;
  try {
    // 1. Verify this home belongs to the logged-in host
    const home = await Home.findOne({ _id: homeId, host: req.session.user._id });
    
    if (!home) {
      console.log("Unauthorized access or home not found");
      return res.redirect('/host-home-list'); // Redirect if not their home
    }

    // 2. Fetch all bookings for this home
    const bookings = await Booking.find({ homeId: homeId })
      .sort({ startDate: 1 }); // Show upcoming bookings first

    // 3. Render the list
    res.render('host/host-bookings', {
      pageTitle: `Bookings for ${home.housename}`,
      bookings: bookings,
      home: home,
      isLoggedIn: req.session.isLoggedIn,
      user: req.session.user
    });
  } catch (err) {
    console.log("Error fetching host bookings:", err);
    next(err);
  }
};